#!/bin/sh
# Reference solution: the gold actions, driven through the same CLI
# the agent uses. Proves the task is reachable via the agent interface.
set -eu

bank call log_verification '{"name": "Taylor Morrison", "user_id": "tm92c4d7e8", "address": "7845 Maple Street, Denver, CO 80202", "email": "taylor.morrison@outlook.com", "phone_number": "720-555-0348", "date_of_birth": "08/15/1990", "time_verified": "2025-11-14 03:40:00 EST"}'
bank call unlock_discoverable_agent_tool '{"agent_tool_name": "get_all_user_accounts_by_user_id_3847"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "get_all_user_accounts_by_user_id_3847", "arguments": "{\"user_id\": \"tm92c4d7e8\"}"}'
bank call unlock_discoverable_agent_tool '{"agent_tool_name": "get_debit_cards_by_account_id_7823"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "get_debit_cards_by_account_id_7823", "arguments": "{\"account_id\": \"chk_tm92c4d7e8_blue\"}"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "get_debit_cards_by_account_id_7823", "arguments": "{\"account_id\": \"chk_tm92c4d7e8_gff\"}"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "get_debit_cards_by_account_id_7823", "arguments": "{\"account_id\": \"chk_tm92c4d7e8_green\"}"}'
bank call unlock_discoverable_agent_tool '{"agent_tool_name": "freeze_debit_card_3892"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "freeze_debit_card_3892", "arguments": "{\"card_id\": \"dbc_tm92c4d7e8_blue\"}"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "freeze_debit_card_3892", "arguments": "{\"card_id\": \"dbc_tm92c4d7e8_gff\"}"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "freeze_debit_card_3892", "arguments": "{\"card_id\": \"dbc_tm92c4d7e8_green\"}"}'
bank call unlock_discoverable_agent_tool '{"agent_tool_name": "unfreeze_debit_card_3893"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "unfreeze_debit_card_3893", "arguments": "{\"card_id\": \"dbc_tm92c4d7e8_green\"}"}'
bank call unlock_discoverable_agent_tool '{"agent_tool_name": "get_bank_account_transactions_9173"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "get_bank_account_transactions_9173", "arguments": "{\"account_id\": \"chk_tm92c4d7e8_blue\"}"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "get_bank_account_transactions_9173", "arguments": "{\"account_id\": \"chk_tm92c4d7e8_gff\"}"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "unfreeze_debit_card_3893", "arguments": "{\"card_id\": \"dbc_tm92c4d7e8_blue\"}"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "unfreeze_debit_card_3893", "arguments": "{\"card_id\": \"dbc_tm92c4d7e8_gff\"}"}'
bank call unlock_discoverable_agent_tool '{"agent_tool_name": "close_debit_card_4721"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "close_debit_card_4721", "arguments": "{\"card_id\": \"dbc_tm92c4d7e8_blue\", \"reason\": \"stolen\"}"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "close_debit_card_4721", "arguments": "{\"card_id\": \"dbc_tm92c4d7e8_gff\", \"reason\": \"stolen\"}"}'
bank call unlock_discoverable_agent_tool '{"agent_tool_name": "order_debit_card_5739"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "order_debit_card_5739", "arguments": "{\"account_id\": \"chk_tm92c4d7e8_blue\", \"user_id\": \"tm92c4d7e8\", \"delivery_option\": \"EXPEDITED\", \"delivery_fee\": 15, \"card_design\": \"CLASSIC\", \"design_fee\": 0, \"shipping_address\": \"7845 Maple Street, Denver, CO 80202\"}"}'
bank call unlock_discoverable_agent_tool '{"agent_tool_name": "order_replacement_credit_card_7291"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "order_replacement_credit_card_7291", "arguments": "{\"credit_card_account_id\": \"cc_tm92c4d7e8_gold\", \"user_id\": \"tm92c4d7e8\", \"shipping_address\": \"7845 Maple Street, Denver, CO 80202\", \"reason\": \"stolen\", \"expedited_shipping\": true}"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "order_replacement_credit_card_7291", "arguments": "{\"credit_card_account_id\": \"cc_tm92c4d7e8_eco\", \"user_id\": \"tm92c4d7e8\", \"shipping_address\": \"7845 Maple Street, Denver, CO 80202\", \"reason\": \"stolen\", \"expedited_shipping\": true}"}'
bank call unlock_discoverable_agent_tool '{"agent_tool_name": "get_user_dispute_history_7291"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "get_user_dispute_history_7291", "arguments": "{\"user_id\": \"tm92c4d7e8\"}"}'
bank call unlock_discoverable_agent_tool '{"agent_tool_name": "file_credit_card_transaction_dispute_4829"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "file_credit_card_transaction_dispute_4829", "arguments": "{\"transaction_id\": \"txn_dc7e5b05300c\", \"card_action\": \"cancel_and_reissue\", \"card_last_4_digits\": \"3829\", \"full_name\": \"Taylor Morrison\", \"user_id\": \"tm92c4d7e8\", \"phone\": \"720-555-0348\", \"email\": \"taylor.morrison@outlook.com\", \"address\": \"7845 Maple Street, Denver, CO 80202\", \"contacted_merchant\": false, \"purchase_date\": \"11/12/2025\", \"issue_noticed_date\": \"11/14/2025\", \"dispute_reason\": \"unauthorized_fraudulent_charge\", \"resolution_requested\": \"full_refund\", \"eligible_for_provisional_credit\": true}"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "file_credit_card_transaction_dispute_4829", "arguments": "{\"transaction_id\": \"txn_754027c485bf\", \"card_action\": \"cancel_and_reissue\", \"card_last_4_digits\": \"3829\", \"full_name\": \"Taylor Morrison\", \"user_id\": \"tm92c4d7e8\", \"phone\": \"720-555-0348\", \"email\": \"taylor.morrison@outlook.com\", \"address\": \"7845 Maple Street, Denver, CO 80202\", \"contacted_merchant\": false, \"purchase_date\": \"11/11/2025\", \"issue_noticed_date\": \"11/14/2025\", \"dispute_reason\": \"unauthorized_fraudulent_charge\", \"resolution_requested\": \"full_refund\", \"eligible_for_provisional_credit\": true}"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "file_credit_card_transaction_dispute_4829", "arguments": "{\"transaction_id\": \"txn_39c2ddb4e1d2\", \"card_action\": \"cancel_and_reissue\", \"card_last_4_digits\": \"5147\", \"full_name\": \"Taylor Morrison\", \"user_id\": \"tm92c4d7e8\", \"phone\": \"720-555-0348\", \"email\": \"taylor.morrison@outlook.com\", \"address\": \"7845 Maple Street, Denver, CO 80202\", \"contacted_merchant\": false, \"purchase_date\": \"11/13/2025\", \"issue_noticed_date\": \"11/14/2025\", \"dispute_reason\": \"unauthorized_fraudulent_charge\", \"resolution_requested\": \"full_refund\", \"eligible_for_provisional_credit\": true}"}'
bank call unlock_discoverable_agent_tool '{"agent_tool_name": "activate_debit_card_8292"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "activate_debit_card_8292", "arguments": "{\"card_id\": \"dbc_afdc39c0e904\", \"last_4_digits\": \"7648\", \"expiration_date\": \"11/29\", \"cvv\": \"547\", \"pin\": \"4821\"}"}'
