#!/bin/sh
# Reference solution: the gold actions, driven through the same CLI
# the agent uses. Proves the task is reachable via the agent interface.
set -eu

bank call log_verification '{"name": "Tyler Washington", "user_id": "tw34a7d9e2", "address": "2847 Pine Street, Unit 12C, Seattle, WA 98101", "email": "tyler.washington.dev@gmail.com", "phone_number": "206-555-8142", "date_of_birth": "09/22/2001", "time_verified": "2025-11-14 03:40:00 EST"}'
bank call unlock_discoverable_agent_tool '{"agent_tool_name": "get_all_user_accounts_by_user_id_3847"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "get_all_user_accounts_by_user_id_3847", "arguments": "{\"user_id\": \"tw34a7d9e2\"}"}'
bank call unlock_discoverable_agent_tool '{"agent_tool_name": "get_debit_cards_by_account_id_7823"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "get_debit_cards_by_account_id_7823", "arguments": "{\"account_id\": \"chk_tw34a7d9e2_green\"}"}'
bank call unlock_discoverable_agent_tool '{"agent_tool_name": "get_bank_account_transactions_9173"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "get_bank_account_transactions_9173", "arguments": "{\"account_id\": \"chk_tw34a7d9e2_green\"}"}'
bank call unlock_discoverable_agent_tool '{"agent_tool_name": "reset_debit_card_pin_6284"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "reset_debit_card_pin_6284", "arguments": "{\"card_id\": \"dbc_tw34a7d9e2_green\", \"last_4_digits\": \"4829\", \"new_pin\": \"2589\"}"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "get_debit_cards_by_account_id_7823", "arguments": "{\"account_id\": \"chk_tw34a7d9e2_evergreen\"}"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "get_bank_account_transactions_9173", "arguments": "{\"account_id\": \"chk_tw34a7d9e2_evergreen\"}"}'
bank call unlock_discoverable_agent_tool '{"agent_tool_name": "close_debit_card_4721"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "close_debit_card_4721", "arguments": "{\"card_id\": \"dbc_tw34a7d9e2_evergreen\", \"reason\": \"fraud_suspected\"}"}'
bank call unlock_discoverable_agent_tool '{"agent_tool_name": "order_debit_card_5739"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "order_debit_card_5739", "arguments": "{\"account_id\": \"chk_tw34a7d9e2_evergreen\", \"user_id\": \"tw34a7d9e2\", \"delivery_option\": \"STANDARD\", \"delivery_fee\": 0, \"card_design\": \"CLASSIC\", \"design_fee\": 0, \"shipping_address\": \"2847 Pine Street, Unit 12C, Seattle, WA 98101\"}"}'
bank call unlock_discoverable_agent_tool '{"agent_tool_name": "file_debit_card_transaction_dispute_6281"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "file_debit_card_transaction_dispute_6281", "arguments": "{\"transaction_id\": \"btxn_92867e549ff2\", \"account_id\": \"chk_tw34a7d9e2_evergreen\", \"card_id\": \"dbc_tw34a7d9e2_evergreen\", \"user_id\": \"tw34a7d9e2\", \"dispute_category\": \"card_present_fraud\", \"transaction_date\": \"11/14/2025\", \"discovery_date\": \"11/14/2025\", \"disputed_amount\": 400.0, \"transaction_type\": \"atm_withdrawal\", \"card_in_possession\": true, \"pin_compromised\": \"yes_observed\", \"contacted_merchant\": false, \"police_report_filed\": false, \"written_statement_provided\": true, \"provisional_credit_eligible\": true, \"customer_max_liability_amount\": 50, \"card_action\": \"close_and_reissue\"}"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "file_debit_card_transaction_dispute_6281", "arguments": "{\"transaction_id\": \"btxn_e5341d2942ef\", \"account_id\": \"chk_tw34a7d9e2_evergreen\", \"card_id\": \"dbc_tw34a7d9e2_evergreen\", \"user_id\": \"tw34a7d9e2\", \"dispute_category\": \"card_present_fraud\", \"transaction_date\": \"11/14/2025\", \"discovery_date\": \"11/14/2025\", \"disputed_amount\": 300.0, \"transaction_type\": \"atm_withdrawal\", \"card_in_possession\": true, \"pin_compromised\": \"yes_observed\", \"contacted_merchant\": false, \"police_report_filed\": false, \"written_statement_provided\": true, \"provisional_credit_eligible\": true, \"customer_max_liability_amount\": 50, \"card_action\": \"close_and_reissue\"}"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "get_debit_cards_by_account_id_7823", "arguments": "{\"account_id\": \"chk_tw34a7d9e2_blue\"}"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "get_bank_account_transactions_9173", "arguments": "{\"account_id\": \"chk_tw34a7d9e2_blue\"}"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "reset_debit_card_pin_6284", "arguments": "{\"card_id\": \"dbc_tw34a7d9e2_blue\", \"last_4_digits\": \"2938\", \"new_pin\": \"5739\"}"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "get_debit_cards_by_account_id_7823", "arguments": "{\"account_id\": \"chk_tw34a7d9e2_lightblue\"}"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "get_bank_account_transactions_9173", "arguments": "{\"account_id\": \"chk_tw34a7d9e2_lightblue\"}"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "close_debit_card_4721", "arguments": "{\"card_id\": \"dbc_tw34a7d9e2_lightblue\", \"reason\": \"fraud_suspected\"}"}'
bank call call_discoverable_agent_tool '{"agent_tool_name": "order_debit_card_5739", "arguments": "{\"account_id\": \"chk_tw34a7d9e2_lightblue\", \"user_id\": \"tw34a7d9e2\", \"delivery_option\": \"STANDARD\", \"delivery_fee\": 0, \"card_design\": \"CLASSIC\", \"design_fee\": 0, \"shipping_address\": \"2847 Pine Street, Unit 12C, Seattle, WA 98101\"}"}'
