#!/usr/bin/env python3
"""Write docs/tools.md — the readable inventory of every bank tool.

This is documentation, not configuration. Which tools an arm exposes is decided
in vendor/toolsets.py; this file just makes the inventory legible, since the
implementations live in a 4,700-line vendored module you should not have to read.

    python tools/document_tools.py
"""

from __future__ import annotations

import inspect
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "vendor"))

from tau2.domains.banking_knowledge.data_model import TransactionalDB  # noqa: E402
from tau2.domains.banking_knowledge.tools import (  # noqa: E402
    KnowledgeTools,
    KnowledgeUserTools,
)
from toolsets import TOOLSETS, allowed  # noqa: E402


def where(cls, name: str) -> str:
    fn = getattr(cls, name, None)
    if fn is None:
        return ""
    try:
        f = pathlib.Path(inspect.getsourcefile(fn)).relative_to(REPO)
        return f"`{f}:{inspect.getsourcelines(fn)[1]}`"
    except Exception:
        return ""


def table(toolkit, cls, discoverable: bool = False) -> list[str]:
    tools = toolkit.get_discoverable_tools() if discoverable else toolkit.get_tools()
    rows = ["| tool | parameters | what it does | source |", "|---|---|---|---|"]
    for name in sorted(tools):
        tool = tools[name]
        if discoverable:
            doc = (inspect.getdoc(tool) or "").split("\n")[0]
            params = ", ".join(
                p for p in inspect.signature(tool).parameters if p != "self"
            )
        else:
            doc = (getattr(tool, "short_desc", "") or "").strip().split("\n")[0]
            fn = (getattr(tool, "openai_schema", None) or {}).get("function", {})
            props = (fn.get("parameters") or {}).get("properties") or {}
            required = set((fn.get("parameters") or {}).get("required") or [])
            params = ", ".join(
                p if p in required else f"_{p}_" for p in props
            )
        rows.append(f"| `{name}` | {params} | {doc[:110]} | {where(cls, name)} |")
    return rows


def main() -> int:
    db = TransactionalDB.load(str(REPO / "data" / "banking_knowledge" / "db.json"))
    agent = KnowledgeTools(db)
    user = KnowledgeUserTools(db)
    every = set(agent.get_tools())

    out = [
        "# Bank tools",
        "",
        "Generated by `python tools/document_tools.py` — do not edit by hand.",
        "",
        "To change what a tool **does**, edit it at the source location below and",
        "rebuild the image. To change which tools an arm **exposes**, edit",
        "`vendor/toolsets.py`.",
        "",
        "## Toolsets",
        "",
        "| name | tools exposed |",
        "|---|---|",
    ]
    for name in TOOLSETS:
        out.append(f"| `{name}` | {len(allowed(name, every))} of {len(every)} |")
    out += [
        "",
        "Select one for a run:",
        "",
        "```bash",
        "--config-override '{\"sandbox\":{\"env\":{\"BANK_TOOLSET\":\"no_discovery\"}}}'",
        "```",
        "",
        "## Agent tools",
        "",
        "Directly callable with `bank call <tool> '<json>'`.",
        "",
    ]
    out += table(agent, KnowledgeTools)
    out += [
        "",
        "## Customer tools",
        "",
        "Reachable with `bank --as user call ...`. Used by the dual-control tasks,",
        "which are out of scope until a user simulator exists.",
        "",
    ]
    out += table(user, KnowledgeUserTools)

    disc = agent.get_discoverable_tools()
    out += [
        "",
        f"## Discoverable tools ({len(disc)})",
        "",
        "Not listed by `bank list`. The agent must find the name in",
        "`/data/documents`, call `unlock_discoverable_agent_tool`, then",
        "`call_discoverable_agent_tool`. **This mechanism is what the benchmark",
        "actually tests** — withholding it is the `no_discovery` arm.",
        "",
    ]
    out += table(agent, KnowledgeTools, discoverable=True)

    path = REPO / "docs" / "tools.md"
    path.write_text("\n".join(out) + "\n")
    print(f"wrote {path.relative_to(REPO)}")
    print(f"  {len(every)} agent, {len(user.get_tools())} user, {len(disc)} discoverable")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
